name: sod_new
description: "A new Flutter project."
publish_to: "none"
version: 0.2.02+4

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.1.0
  http: ^1.2.0
  in_app_update: ^4.2.3
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
